### ISSUE TITLE
Threshold selection

### ISSUE THREAD

**Issue by Bin-Ma** [BioinformaticsLabAtMUN/Promotech#11]
Hi @BioinformaticsLabAtMUN,
I tried to predict E. coli promoter using Promotech recently. With the threshold equal to 0.6, there are 17620 promoter sites predicted. However, only about 5000 genes are available in E. coli. I don't know how to persuasively set the threshold.
Looking forware to your help.
Best,
Bin

**Comment by liampshaw** [comment]
I'm also interested in this question. 

Assuming I understand the score for each 40nt sequence correctly, it is the probability of that sequence containing a promoter (from the particular model used e.g. RF-HOT).

In the paper [Fig. 4](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02514-9/figures/4) the thresholds used for the comparison to true promoter locations are 0.6 and 0.5. These predictions are for _E. coli_ K-12 [`NC_000913.3`](https://www.ncbi.nlm.nih.gov/nuccore/nc_000913). Looking at them makes me think that for _E. coli_ a threshold of 0.5 predicts too many promoter locations and a threshold of 0.6 misses some. Though that's qualitative based only on looking at the figure. 

Unless I missed it the paper does not include explicit discussion of the choice of threshold, particularly how it might vary for different species. Any guidance from the authors would be appreciated. 

Thanks!

**Comment by BioinformaticsLabAtMUN** [comment]
Excellent question.  Yes, the probability returned is the probability of that sequence containing a promoter as per the model used (models do not always agree). Predicted promoter-containing sequences might overlap so it would be recommendable to merge overlapping predicted sequences.  Additionally, in our evaluation we noticed that true positives tend to have a cluster of sequences with high probability of containing a promoter around them.

The threshold is a trade off between having too many false promoters and missing real promoters (to have an idea how the program will perform you can look at the precision-recall curves in the paper). We didn't look at the effect of the thresholds in specific species.

We recommend the threshold of 0.6 as in our experiments  achieved the highest Area under the Precision-Recall curve.

An idea (which we didn't evaluate) would be to predict promoters at a threshold of 0.5 with different models but then only take the intersection of the predictions.
