### ISSUE TITLE
RF-HOT.model not found

### ISSUE THREAD

**Issue by Kevi84LA** [BioinformaticsLabAtMUN/Promotech#13]
Hello,

I've been working with Promotech v1.0, commit number [221b257].
I've attempted to predict the entire genome of Mycobacterium tuberculosis using the following commands:
`python promotech.py -pg -m RF-HOT -f path_to_fasta -o results`
and
`python promotech.py -g -t 0.6 -i results -o results`

However, I've encountered an error, which you can see below:

![issues](https://github.com/BioinformaticsLabAtMUN/Promotech/assets/31652273/fc10229b-c505-45a3-90f9-269b296a01f7)

I installed Promotech using Conda.
Can you help me understand and resolve this issue?

Thanks in advance.

**Comment by mmpust** [comment]
Hi,
were you able to solve the problem?
I am having the same issue.
Thanks!
```
OUTPUT SAMPLE WITH LEN (1,): 
ATGGATTCTTTCAAGGACGTTTTAGAGGCCGCCCAGGCAT


 CONVERTING DATA
N/A% (0 of 1) |                                                                                                                                               | Elapsed Time: 0:00:00 ETA:  --:--:--

 HOT ENCODED SEQUENCES GENERATED SUCCESSFULLY. 


   A  G  C  T  A ...  T  A  G  C  T
0  1  0  0  0  0 ...  0  0  0  0  1

[1 rows x 160 columns]

TIME ELAPSED FROM START (HOUR:MIN:SEC): 00:00:09

LOADING ML MODEL models/RF-HOT.model

Traceback (most recent call last):
  File "/home/Promotech/promotech.py", line 72, in <module>
    model_type      = args.model
  File "/home/Promotech/sequences/process_sequences.py", line 89, in predictSequences
    start_time=start_time
  File "/home/Promotech/sequences/process_sequences.py", line 49, in predictSequencesFromString
    model = joblib.load(model_path)
  File "/home/miniconda3/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 577, in load
    with open(filename, 'rb') as f:

FileNotFoundError: [Errno 2] No such file or directory: 'models/RF-HOT.model'
```

**Comment by mmpust** [comment]
Any update?

**Comment by mmpust** [comment]
the models can be downloaded from
http://www.cs.mun.ca/~lourdes/public/PromoTech_models/
