### ISSUE TITLE
ModuleNotFoundError: No module named 'ui.GUI'

### ISSUE THREAD

**Issue by jiaobian** [BioinformaticsLabAtMUN/Promotech#6]
Hi,
I'm trying to run Promotech for 40 nucleotide sequences, but failed because of the following error:

`python promotech.py -s -m RF-HOT -f /Home/promoter/liv-1.fasta -o results`
`Traceback (most recent call last):`
`File "promotech.py", line 5, in <module>`
`from ui.GUI import Promotech_UI`
`ModuleNotFoundError: No module named 'ui.GUI'`

Hope you can help me solve this problem.

**Comment by BioinformaticsLabAtMUN** [comment]
Did you clone the repository? The folder ui and the files located there must be in Promotech's folder; otherwise, it won't find that code.
