### ISSUE TITLE
Installation guide?

### ISSUE THREAD

**Issue by thh32** [BioinformaticsLabAtMUN/Promotech#8]
I am a little confused how to install your tool. I have created the conda environment, and downloaded the two models, but am I also ment to download the GitHub repository? No 'model' folder appears in the environment, but this is unclear at this stage.

Thanks,
Tom

**Comment by BioinformaticsLabAtMUN** [comment]
If you are using conda you need to download from GitHub the yml file corresponding to your operating system (mac or linux).  Cloning the GitHub repository will also download these yml files.

Independently from whether you use conda or not, you still need to download the models from this link: http://www.cs.mun.ca/~lourdes/public/PromoTech_models/
and place them in a folder called models

Hope this helps.
