### ISSUE TITLE
using?

### ISSUE THREAD

**Issue by wwwt113** [BioinformaticsLabAtMUN/Promotech#9]
I have a question about this:
raceback (most recent call last):
  File "/home/Downloads/Promotech/promotech.py", line 79, in <module>
    parseGenome40NTSequences(
  File "/home/Downloads/Promotech/genome/process_genome.py", line 81, in parseGenome40NTSequences
    chrom, cutted_seqs = genomeSlidingWindow(fasta_file_path=fasta_file_path, log_file=log_file, promoter_size=promoter_size, step_size=step_size, print_fn=print_fn)
  File "/home/Downloads/Promotech/genome/process_genome.py", line 52, in genomeSlidingWindow
    cutted_seqs = np.array([ genome[i:i+promoter_size] for i in progressbar.progressbar( range( 0, n_samples, step_size ) ) ]) 
TypeError: 'module' object is not callable
and I don't know how to solve it, please help me. This is getting on my nerves.

**Comment by BioinformaticsLabAtMUN** [comment]
Are you using the conda environment we provided to run promotech?

**Comment by Bin-Ma** [comment]
Hi @BioinformaticsLabAtMUN ,
I have the same problem. I tried to employ the promotech in testing dataset with the  command `python promotech.py -pg -m RF-HOT -f examples/genome/ECOLI_2.fasta -o results`. I confirm the promotech was employed in `promotech_env`.

Bin

**Comment by Bin-Ma** [comment]
Hi @wwwt113 ,
I solve the problem ! You can try to check the version of progressbar. I remove the progressbar package from pip and conda, and reinstall it by pip with the command `pip install progressbar2`. Finally, the promotech worked well.

Bin

**Comment by wwwt113** [comment]
> Hi @wwwt113 , I solve the problem ! You can try to check the version of progressbar. I remove the progressbar package from pip and conda, and reinstall it by pip with the command `pip install progressbar2`. Finally, the promotech worked well.
> 
> Bin

Hi @Bin-Ma ,
Thank you for your answer. I did not use conda, so there was an error, but after changing the version of scipy, the promotech was ready to run.   `pip install scipy ==1.8.1`   Like that. Thank you again for your peply.

_

**Comment by BioinformaticsLabAtMUN** [comment]
Thank you for indicating how you solved the issue!
